language: elixir
elixir:
  - 1.4.2
script:
  - mix credo
  - mix test
  - MIX_ENV=prod mix do compile --warnings-as-errors, archive.build, archive.install --force
  - MIX_ENV=prod mix dialyzer --halt-exit-status
